server:
  port: ${PTKNOW_PORT}

spring:
  datasource:
    url: jdbc:postgresql://${PTKNOW_DATASOURCE_ADDRESS}/${PTKNOW_DATASOURCE_NAME}
    username: ${PTKNOW_DATASOURCE_USERNAME}
    password: ${PTKNOW_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ptknow

security:
  jwt: ${SECRET_JWT_KEY}
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7